
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cozhpjchdrjukabmcngr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvemhwamNoZHJqdWthYm1jbmdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTE2ODcsImV4cCI6MjA2MDEyNzY4N30.pyMBOxDUDlTuAqCNYscsedLzm0-RKB2ngIrVK01u9c8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
